---

- name: Installing neovim's Node LSPs
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ neovim_node_lsps }}"
  tags:
    - neovim

- name: Upgrade neovim's Node LSPs
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items: "{{ neovim_node_lsps }}"
  tags:
    - upgrade
