---
- name: Get fish directory
  command: brew --prefix fish
  register: fish_dir
  changed_when: false
  tags:
    - neovim

- name: Get current node version
  register: node_version
  shell:
    cmd: nvm current
    executable: "{{ fish_dir.stdout }}/bin/fish"
  tags:
    - neovim
  changed_when: false

- name: Installing neovim's Node LSPs
  npm:
    name: "{{ item }}"
    global: yes
    executable: "{{ ansible_env.HOME }}/.local/share/nvm/{{ node_version.stdout }}/bin/npm"
  with_items: "{{ neovim_node_lsps }}"
  tags:
    - neovim

- name: Upgrade neovim's Node LSPs
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
    executable: "{{ ansible_env.HOME }}/.local/share/nvm/{{ node_version.stdout }}/bin/npm"
  with_items: "{{ neovim_node_lsps }}"
  tags:
    - upgrade
