---
- name: Installing neovim formulas
  homebrew:
    name: "{{ neovim_formulas }}"
    state: present
  when: neovim_formulas | list
  tags:
    - neovim

- name: Adding universal-tags tap
  homebrew_tap:
    name: universal-ctags/universal-ctags
    state: present
  tags:
    - neovim

- name: Installing Ruby environment
  include_tasks: ruby.yml
  tags:
    - neovim

- name: Installing Python environment
  include_tasks: python.yml
  tags:
    - neovim

- name: Installing LSPs
  include_tasks: lsps.yml
  tags:
    - neovim

- name: Installing packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    depth: "1"
    force: yes
    recursive: yes
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - neovim

- name: Updating neovim's configuration folder
  copy:
    src: "{{ neovim_config_path }}"
    dest: "{{ ansible_env.HOME }}/.config"
  when: neovim_config_path | string
  tags:
    - neovim

- name: Installing neovim plugins
  shell: >
    nvim --headless
    -c 'autocmd User PackerComplete quitall'
    -c 'silent! PackerSync'
    -c 'silent! TSInstall maintained'
    -c 'silent! TSUpdate' &> /dev/null < /dev/tty
  changed_when: false
  tags:
    - neovim

- name: Updating neovim plugins
  shell: >
    nvim --headless
    -c 'autocmd User PackerComplete quitall'
    -c 'silent! PackerSync'
    -c 'silent! TSUpdate' &> /dev/null < /dev/tty
  changed_when: false
  tags:
    - upgrade
