---

- name: Checking Installed Python interpreters
  command: pyenv versions
  register: pyenv_versions
  changed_when: false

- name: Storing pyenv root
  command: pyenv root
  register: pyenv_root
  changed_when: false

- name: Installing Python interpreters for neovim
  command: pyenv install {{ neovim_python_version }}
  when: not (neovim_python_version in (pyenv_versions.stdout_lines | map('trim') | list))

- name: Installing Python neovim host clients
  pip:
    name:
      - pynvim
      - neovim
      - msgpack
    executable: "{{ pyenv_root.stdout }}/versions/{{ neovim_python_version }}/bin/pip"
    state: latest

- name: Rehashing environments
  command: pyenv rehash
  changed_when: false
