---
- name: Storing rbenv root
  command: rbenv root
  register: rbenv_root
  changed_when: false

- name: Checking installed ruby interpreters
  command: ls {{ rbenv_root.stdout }}/versions
  register: rbenv_versions
  changed_when: false

- name: Installing Ruby interpreter for neovim
  command: rbenv install {{ lookup('env', 'RBENV_VERSION') | default(neovim_ruby_version) }}
  when: not ((lookup('env', 'RBENV_VERSION') | default(neovim_ruby_version)) in (rbenv_versions.stdout_lines | map('trim') | list))

- name: Installing Ruby's neovim gems
  gem:
    name: "{{ item }}"
    state: latest
    user_install: no
    executable: "{{ rbenv_root.stdout }}/versions/{{ lookup('env', 'RBENV_VERSION') | default(neovim_ruby_version) }}/bin/gem"
  with_items:
    - neovim
    - bundler
    - rubocop
    - solargraph

- name: Rehashing environments
  command: rbenv rehash
  changed_when: false
